# Generated by Django 4.2 on 2023-04-28 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_eng_level_customuser_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
