# Generated by Django 4.2 on 2023-04-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='reviewed_user_id',
        ),
    ]
